app:
  owner: "Aida Sembai"
  group: "IT1-2406IS"
  mail:
    from: "aida@example.com"
    retry-count: 3
    timeout: 5s
    enabled: true
  rate-limit:
    requests-per-minute: 60
    burst: 20

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,env,configprops,conditions